config/routes.rb
Rails.application.routes.draw do
  resources :gamers

  root 'gamers#new'

end

app/models/gamer.rb
class Gamer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController
  before_action :set_gamer, only: [:show, :edit, :update, :destroy]

  # GET /gamers
  # GET /gamers.json
  def index
    @gamer = Gamer.new
  end

  # GET /gamers/1
  # GET /gamers/1.json
  def show
    @gamers = Gamer.all
  end

  # GET /gamers/new
  def new
    @gamer = Gamer.new
  end

  # GET /gamers/1/edit
  def edit
  end

  # POST /gamers
  # POST /gamers.json
  def create
    @gamer = Gamer.new(gamer_params)

    respond_to do |format|
      if @gamer.save
        format.html { redirect_to @gamer, notice: 'Gamer was successfully created.' }
        format.json { render :show, status: :created, location: @gamer }
      else
        format.html { render :new }
        format.json { render json: @gamer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gamers/1
  # PATCH/PUT /gamers/1.json
  def update
    respond_to do |format|
      if @gamer.update(gamer_params)
        format.html { redirect_to @gamer, notice: 'Gamer was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamer }
      else
        format.html { render :edit }
        format.json { render json: @gamer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamers/1
  # DELETE /gamers/1.json
  def destroy
    @gamer.destroy
    respond_to do |format|
      format.html { redirect_to gamers_url, notice: 'Gamer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gamer
    @gamer = Gamer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gamer_params
    params.require(:gamer).permit(:name, :email, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gamers_helper.rb
module GamersHelper
end

app/views/gamers/_form.html.erb
<%= form_for(@gamer) do |f| %>
  <% if @gamer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamer.errors.count, "error") %> prohibited this gamer from being saved:</h2>
      <ul>
      <% @gamer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <md-dialog-actions layout="row">
    <span flex></span>
    <md-button type="submit" name="commit" ng-click="answer('useful')" style="margin-right:20px;">
      Jogar
    </md-button>
  </md-dialog-actions>
<% end %>

app/views/gamers/_formscript.html.erb
<script type="text/ng-template" id="dialog1.tmpl.html">
  <md-dialog aria-label="Novo Jogador"  ng-cloak>
    <form>
      <md-toolbar>
        <div class="md-toolbar-tools">
          <h2>O Guru não sabe de tudo. Quem é você?</h2>
          <span flex></span>
          <md-button class="md-icon-button" ng-click="cancel()">
            <md-icon md-svg-src="img/icons/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
          </md-button>
        </div>
      </md-toolbar>

      <md-dialog-content>
        <div class="md-dialog-content">
          <%= render 'form' %>
        </div>
      </md-dialog-content>
    </form>
  </md-dialog>
</script>

app/views/gamers/edit.html.erb
<h1>Editar Jogador</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @gamer,  class: "button" %> |
<%= link_to 'Voltar', gamers_path,  class: "button" %>

app/views/gamers/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="text-center">Adivinhar</h2>

  <section class="row">
    <div class="small-10 small-centered guru-presenter-symbol center">

    </div>
  </section>
  <div class="row numbers">
    <div class="small-12 medium-8 columns small-centered">
      <section class="row">
        <% for i in 0..95 %>
        <div class="small-3 medium-2 large-1 columns number text-center">
          <strong>
            <%= rand(0..99) %>
          </strong>
        </div>
        <% end %>
      </section>
    </div>
  </div>

app/views/gamers/new.html.erb
<div class="new-gamer">
  <div ng-controller="NewGamerCtrl" class="dialogdemoBasicUsage" id="popupContainer" ng-cloak="">
    <div class="dialog-demo-content" layout="row" layout-wrap="" layout-margin="" layout-align="center">
      <span ng-init="showAdvanced($event)"></span>
      <%= render 'formscript' %>
    </div>
  </div>
</div>

app/views/gamers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gamer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @gamer.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @gamer.age %>
</p>

<%= link_to 'Editar', edit_gamer_path(@gamer),  class: "button" %> |
<%= link_to 'Voltar', gamers_path,  class: "button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Guru" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="body-app" ng-app="GuruApp">
    <section class="row header">
      <div class="small-4 columns text-left">
        <h1>Guru</h1>
      </div>
      <div class="small-8 medium-4 columns text-right gamer">
      </div>
    </section>
    <div class="content">
      <%= yield %>
    </div>
    <footer class="header">
    </footer>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  </body>
</html>